language: cpp

install:
# Install conan
- pip install --user -q conan
# Automatic detection of your arch, compiler, etc.
- conan user

script:
  - mkdir -p build && cd build
  - conan install .. --build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ./bin/test_hello
